### ISSUE TITLE
Unable to receive notifications

### ISSUE THREAD

**Issue by phoeluga** [foxriver76/ioBroker.notification-manager#6]
Hi, I am in the process of preparing the `synochat` adapter to react to messages in general and in special to notifications from the Notification-Manager.
During the first testing phase I came across two findings.

**Describe the bug:**  

1. When using the Test button, I was not able to receive an message that was pushed to the `synochat` adapter instance.
In general the `synochat` adapter is now able to react on messages. (Tested with a small script)

However, the only output in the debug log from Notification-Manager when pressing the button is:
```
Send test message for scope "system" and category "memIssues"
```

2. To test whether a "real" notification can be sent, I forced an adapter (Not the Notification-Manager) instance to be in a restart loop.
This causes the Notification Manager instance to crash:

```
notification-manager.0
	2023-07-21 13:33:28.835	error	Cannot read properties of undefined (reading 'en')
notification-manager.0
	2023-07-21 13:33:28.835	error	TypeError: Cannot read properties of undefined (reading 'en') at NotificationManager.localize (/opt/iobroker/node_modules/iobroker.notification-manager/build/main.js:180:52) at async NotificationManager.sendNotifications (/opt/iobroker/node_modules/iobroker.notification-manager/build/main.js:140:20) at async NotificationManager.handleNotifications (/opt/iobroker/node_modules/iobroker.notification-manager/build/main.js:90:7) at async NotificationManager.onStateChange (/opt/iobroker/node_modules/iobroker.notification-manager/build/main.js:78:5)
notification-manager.0
	2023-07-21 13:33:28.834	error	unhandled promise rejection: Cannot read properties of undefined (reading 'en')
notification-manager.0
	2023-07-21 13:33:28.834	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
notification-manager.0
	2023-07-21 13:33:28.831	info	Send notification "system.restartLoop" to "synochat.0"
notification-manager.0
	2023-07-21 13:33:28.830	debug	Received notifications from "system.host.iobroker": {"system":{"categories":{"restartLoop":{"instances":{"system.adapter.synochat.1":{"messages":[{"message":"Restart loop detected","ts":1689939208823}]}},"description":{"en":"An adapter instance is frequently crashing on startup and was stopped because of this. The log file needs to be checked before restarting the instance.","de":"Eine Adapterinstanz stürzt beim Start häufig ab und wurde aus diesem Grund gestoppt. Die Protokolldatei muss vor dem Neustart der Instanz überprüft werden.","ru":"Экземпляр адаптера часто дает сбой при запуске и был остановлен из-за этого. Перед перезапуском экземпляра необходимо проверить файл журнала.","pt":"Uma instância do adaptador frequentemente falha na inicialização e foi interrompida por causa disso. O arquivo de log precisa ser verificado antes de reiniciar a instância.","nl":"Een adapterinstantie crasht vaak bij het opstarten en is hierdoor gestopt. Het logboekbestand moet worden gecontroleerd voordat het exemplaar opnieuw wordt opgestart.","fr":"Une instance d'adaptateur plante fréquemment au démarrage et a été arrêtée à cause de cela. Le fichier journal doit être vérifié avant de redémarrer l'instance.","it":"Un'istanza dell'adattatore si blocca spesso all'avvio ed è stata interrotta per questo motivo. Il file di registro deve essere controllato prima di riavviare l'istanza.","es":"Una instancia de adaptador falla con frecuencia al iniciarse y se detuvo debido a esto. Es necesario comprobar el archivo de registro antes de reiniciar la instancia.","pl":"Instancja adaptera często ulega awarii podczas uruchamiania i została z tego powodu zatrzymana. Plik dziennika należy sprawdzić przed ponownym uruchomieniem instancji.","zh-cn":"适配器实例在启动时经常崩溃，因此已被停止。重新启动实例之前，需要检查日志文件。"},"name":{"en":"Issues with frequently crashing adapter instances","de":"Probleme mit häufig abstürzenden Adapterinstanzen","ru":"Проблемы с частыми сбоями экземпляров адаптера","pt":"Problemas com falhas frequentes de instâncias do adaptador","nl":"Problemen met vaak crashende adapterinstanties","fr":"Problèmes avec les instances d'adaptateur qui plantent fréquemment","it":"Problemi con le istanze dell'adattatore che si arrestano frequentemente","es":"Problemas con instancias de adaptador que fallan con frecuencia","pl":"Problemy z często zawieszającymi się instancjami adaptera","zh-cn":"适配器实例频繁崩溃的问题"},"severity":"alert"}}}}
notification-manager.0
	2023-07-21 13:33:28.826	debug	Request notifications from "system.host.iobroker"
notification-manager.0
	2023-07-21 13:33:28.826	info	New notification on "iobroker" detected
```

This is the message, that is sent if the localization for scopeOrCategory will be ignored/removed - Hope this might be helpful:

```
{
    "host": "system.host.iobroker",
    "scope": {},
    "category": {
      "instances": {
        "system.adapter.synochat.1": {
          "messages": [
            {
              "message": "Restart loop detected",
              "ts": 1689939208823
            }
          ]
        },
        "system.adapter.notification-manager.0": {
          "messages": [
            {
              "message": "Restart loop detected",
              "ts": 1689940386147
            }
          ]
        }
      },
      "description": {
        "en": "An adapter instance is frequently crashing on startup and was stopped because of this. The log file needs to be checked before restarting the instance.",
        "de": "Eine Adapterinstanz stürzt beim Start häufig ab und wurde aus diesem Grund gestoppt. Die Protokolldatei muss vor dem Neustart der Instanz überprüft werden.",
        "ru": "Экземпляр адаптера часто дает сбой при запуске и был остановлен из-за этого. Перед перезапуском экземпляра необходимо проверить файл журнала.",
        "pt": "Uma instância do adaptador frequentemente falha na inicialização e foi interrompida por causa disso. O arquivo de log precisa ser verificado antes de reiniciar a instância.",
        "nl": "Een adapterinstantie crasht vaak bij het opstarten en is hierdoor gestopt. Het logboekbestand moet worden gecontroleerd voordat het exemplaar opnieuw wordt opgestart.",
        "fr": "Une instance d'adaptateur plante fréquemment au démarrage et a été arrêtée à cause de cela. Le fichier journal doit être vérifié avant de redémarrer l'instance.",
        "it": "Un'istanza dell'adattatore si blocca spesso all'avvio ed è stata interrotta per questo motivo. Il file di registro deve essere controllato prima di riavviare l'istanza.",
        "es": "Una instancia de adaptador falla con frecuencia al iniciarse y se detuvo debido a esto. Es necesario comprobar el archivo de registro antes de reiniciar la instancia.",
        "pl": "Instancja adaptera często ulega awarii podczas uruchamiania i została z tego powodu zatrzymana. Plik dziennika należy sprawdzić przed ponownym uruchomieniem instancji.",
        "zh-cn": "适配器实例在启动时经常崩溃，因此已被停止。重新启动实例之前，需要检查日志文件。"
      },
      "name": {
        "en": "Issues with frequently crashing adapter instances",
        "de": "Probleme mit häufig abstürzenden Adapterinstanzen",
        "ru": "Проблемы с частыми сбоями экземпляров адаптера",
        "pt": "Problemas com falhas frequentes de instâncias do adaptador",
        "nl": "Problemen met vaak crashende adapterinstanties",
        "fr": "Problèmes avec les instances d'adaptateur qui plantent fréquemment",
        "it": "Problemi con le istanze dell'adattatore che si arrestano frequentemente",
        "es": "Problemas con instancias de adaptador que fallan con frecuencia",
        "pl": "Problemy z często zawieszającymi się instancjami adaptera",
        "zh-cn": "适配器实例频繁崩溃的问题"
      },
      "severity": "alert"
    }
  }
```

**Versions:**  
 - Adapter version: 0.1.1
 - JS-Controller version: 4.0.24
 - Node version: 18.17.0
 - Operating system: docker

**Comment by foxriver76** [comment]
Test button only works with controller 5.0.8 and above

**Comment by phoeluga** [comment]
Thank you for the exhaustive explanation. Both described problems are no longer existent after a controller update.
Would be good to keep this requirement in the readme, in case other developers should stumble over this too.
Thanks anyway

**Comment by foxriver76** [comment]
Sorry only mobile and short on time. I don’t think an exhaustive explanation helps, however  there has been a bug that adapters cannot register notifications because they were sent to the wrong topic on database level thus also the notification manager was not able to register notifications. I will add a controller dependency when we are going towards stable.
